# This is the neoforge.mods.toml file for Chest Cavity
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TheCrazy8/chestcavity/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/TheCrazy8/chestcavity"
logoFile="assets/chestcavity/icon.png"
authors="David Troyer"
description='''
Chest Cavity lets you use a 'chest opener' to access a secondary inventory. There are some items already in it, but those probably aren't important so you can take them out to make room for other stuff.

It also adds a variety of drops that are similar to the junk you discarded from your extra storage.
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="chestcavity.mixins.json"

# Dependencies
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
